In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("iris.csv")
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
training,test = train_test_split(
             data, test_size = 0.3, random_state=42)

In [4]:
training

     sepal.length  sepal.width  petal.length  petal.width     variety
81            5.5          2.4           3.7          1.0  Versicolor
133           6.3          2.8           5.1          1.5   Virginica
137           6.4          3.1           5.5          1.8   Virginica
75            6.6          3.0           4.4          1.4  Versicolor
109           7.2          3.6           6.1          2.5   Virginica
..            ...          ...           ...          ...         ...
71            6.1          2.8           4.0          1.3  Versicolor
106           4.9          2.5           4.5          1.7   Virginica
14            5.8          4.0           1.2          0.2      Setosa
92            5.8          2.6           4.0          1.2  Versicolor
102           7.1          3.0           5.9          2.1   Virginica

[105 rows x 5 columns]

In [5]:
test

     sepal.length  sepal.width  petal.length  petal.width     variety
73            6.1          2.8           4.7          1.2  Versicolor
18            5.7          3.8           1.7          0.3      Setosa
118           7.7          2.6           6.9          2.3   Virginica
78            6.0          2.9           4.5          1.5  Versicolor
76            6.8          2.8           4.8          1.4  Versicolor
31            5.4          3.4           1.5          0.4      Setosa
64            5.6          2.9           3.6          1.3  Versicolor
141           6.9          3.1           5.1          2.3   Virginica
68            6.2          2.2           4.5          1.5  Versicolor
82            5.8          2.7           3.9          1.2  Versicolor
110           6.5          3.2           5.1          2.0   Virginica
12            4.8          3.0           1.4          0.1      Setosa
36            5.5          3.5           1.3          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
19            5.1          3.8           1.5          0.3      Setosa
56            6.3          3.3           4.7          1.6  Versicolor
104           6.5          3.0           5.8          2.2   Virginica
69            5.6          2.5           3.9          1.1  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
132           6.4          2.8           5.6          2.2   Virginica
29            4.7          3.2           1.6          0.2      Setosa
127           6.1          3.0           4.9          1.8   Virginica
26            5.0          3.4           1.6          0.4      Setosa
128           6.4          2.8           5.6          2.1   Virginica
131           7.9          3.8           6.4          2.0   Virginica
145           6.7          3.0           5.2          2.3   Virginica
108           6.7          2.5           5.8          1.8   Virginica
143           6.8          3.2           5.9          2.3   Virginica
45            4.8          3.0           1.4          0.3      Setosa
30            4.8          3.1           1.6          0.2      Setosa
22            4.6          3.6           1.0          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
65            6.7          3.1           4.4          1.4  Versicolor
11            4.8          3.4           1.6          0.2      Setosa
42            4.4          3.2           1.3          0.2      Setosa
146           6.3          2.5           5.0          1.9   Virginica
51            6.4          3.2           4.5          1.5  Versicolor
27            5.2          3.5           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
32            5.2          4.1           1.5          0.1      Setosa
142           5.8          2.7           5.1          1.9   Virginica
85            6.0          3.4           4.5          1.6  Versicolor
86            6.7          3.1           4.7          1.5  Versicolor
16            5.4          3.9           1.3          0.4      Setosa
10            5.4          3.7           1.5          0.2      Setosa

In [14]:
KNN(test.values, training.values,2)
# when 2 neighbours are decided .. no.35 is an error
# proof it's not just concatinated

   Exact Output Predicted Output
0    Versicolor       Versicolor
1        Setosa           Setosa
2     Virginica        Virginica
3    Versicolor       Versicolor
4    Versicolor       Versicolor
5        Setosa           Setosa
6    Versicolor       Versicolor
7     Virginica        Virginica
8    Versicolor        Virginica
9    Versicolor       Versicolor
10    Virginica        Virginica
11       Setosa           Setosa
12       Setosa           Setosa
13       Setosa           Setosa
14       Setosa           Setosa
15   Versicolor       Versicolor
16    Virginica        Virginica
17   Versicolor       Versicolor
18   Versicolor       Versicolor
19    Virginica        Virginica
20       Setosa           Setosa
21    Virginica        Virginica
22       Setosa           Setosa
23    Virginica        Virginica
24    Virginica        Virginica
25    Virginica        Virginica
26    Virginica        Virginica
27    Virginica        Virginica
28       Setosa           Setosa
29       Setosa           Setosa
30       Setosa           Setosa
31       Setosa           Setosa
32   Versicolor       Versicolor
33       Setosa           Setosa
34       Setosa           Setosa
35    Virginica       Versicolor
36   Versicolor       Versicolor
37       Setosa           Setosa
38       Setosa           Setosa
39       Setosa           Setosa
40    Virginica        Virginica
41   Versicolor       Versicolor
42   Versicolor       Versicolor
43       Setosa           Setosa
44       Setosa           Setosa

In [8]:
def addNeighbours(array, k):
        neighbours = []
        array = sorted(array)
        neighbours.append(array[:k])
        return neighbours

In [9]:
def KNN (test, training, k):
    if k > len(training):
        return 'k is larger than set'
    elif k<1:
        return 'please make sure that k>0'
    else:
        array = []
        arrayClass = []
        neighbours = []
        for i in range(len(test)):
            distance = []
            Distance_class = []
            for j in range(len(training)):
                value = 0.0
                for m in range(len(test[0])-1):
                    value += (np.abs(((test[i][m] - training[j][m]))))
                distance.append(value)
                Distance_class.append([value , training[j][-1]])
            array.append(distance)
            arrayClass.append(Distance_class)
            neighbours += (addNeighbours(array[i], k))
        arrayClass = np.array(arrayClass)
        neighbours = np.array(neighbours)
        # array classes is 3d
        # the big list holding all distance,class for all test points to all training points
        # smaller lists holding multiple distance,class for one test point and multiple training point
        # smallest one holding a distance, class between one test point and one training point
        return finalize(test, training, arrayClass, neighbours)

In [13]:
def finalize ( test, training, array, neighbours):
    predicted = [] #holds smallest k distances in output list
    expected = []
    output = [] #holds all outputs
    appended = []
    for i in range(len(neighbours)):
        classes=[]
        for j in range(len(neighbours[0])):
            for m in range((len(array[0])-1)):
                if float(neighbours[i][j]) == float(array[i][m][:-1]):
                    if (i,j) not in appended:
                        appended.append((i,j))
                        classes.append(array[i][m][-1])
        expected.append(test[i][-1])
        output.append(classes)
        
    output = np.array(output, dtype=object)
    for i in output:
        predicted.append(Count(i))
        
    dic= {
        'Exact Output':expected,
        'Predicted Output':predicted}    
    table = pd. DataFrame(dic)
    return table

In [10]:
def Count(output):
    count = {}
    for variety in output:
            if variety not in count:
                count [variety] = 1
            else:
                 count[variety] += 1
    return predict(count)

In [11]:
def predict(output):
    maximum = 0.0
    classifier = ''
    for value in output.values():
        if value > maximum:
            maximum = value
    for key in output:
        if output[key] == maximum:
            classifier = key
    return classifier